apiVersion: v1
kind: ServiceMonitor
metadata:
  name: gait-detection-metrics
  namespace: default
  labels:
    app: gait-detection
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: gait-detection
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gait-detection-alerts
  namespace: default
  labels:
    app: gait-detection
    prometheus: kube-prometheus
spec:
  groups:
  - name: gait-detection.rules
    rules:
    - alert: GaitDetectionHighCPU
      expr: rate(container_cpu_usage_seconds_total{pod=~"gait-detection-app-.*"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
        service: gait-detection
      annotations:
        summary: "High CPU usage in Gait Detection pod"
        description: "Pod {{ $labels.pod }} has high CPU usage: {{ $value }}"

    - alert: GaitDetectionHighMemory
      expr: container_memory_usage_bytes{pod=~"gait-detection-app-.*"} / container_spec_memory_limit_bytes > 0.85
      for: 5m
      labels:
        severity: warning
        service: gait-detection
      annotations:
        summary: "High memory usage in Gait Detection pod"
        description: "Pod {{ $labels.pod }} has high memory usage: {{ $value }}"

    - alert: GaitDetectionPodDown
      expr: up{job="gait-detection-service"} == 0
      for: 1m
      labels:
        severity: critical
        service: gait-detection
      annotations:
        summary: "Gait Detection pod is down"
        description: "Gait Detection pod has been down for more than 1 minute"

    - alert: GaitDetectionHighErrorRate
      expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) > 0.05
      for: 2m
      labels:
        severity: warning
        service: gait-detection
      annotations:
        summary: "High error rate in Gait Detection"
        description: "Error rate is {{ $value }} errors per second"

    - alert: GaitDetectionSlowResponse
      expr: histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
        service: gait-detection
      annotations:
        summary: "Slow response time in Gait Detection"
        description: "95th percentile response time is {{ $value }}s"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-gait-detection
  namespace: monitoring
  labels:
    app: gait-detection
    grafana_dashboard: "1"
data:
  gait-detection-dashboard.json: |
    {
      "annotations": {
        "list": []
      },
      "description": "Gait Detection Application Dashboard",
      "editable": true,
      "fiscalYearStartMonth": 0,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "datasource": {
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "vis": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "percent"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "expr": "rate(container_cpu_usage_seconds_total{pod=~\"gait-detection-app-.*\"}[5m]) * 100",
              "interval": "",
              "legendFormat": "CPU Usage - {{pod}}",
              "refId": "A"
            }
          ],
          "title": "CPU Usage",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "vis": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "bytes"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "expr": "container_memory_usage_bytes{pod=~\"gait-detection-app-.*\"}",
              "interval": "",
              "legendFormat": "Memory Usage - {{pod}}",
              "refId": "A"
            }
          ],
          "title": "Memory Usage",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "vis": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "reqps"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "id": 3,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "expr": "rate(nginx_http_requests_total{service=\"gait-detection-service\"}[5m])",
              "interval": "",
              "legendFormat": "Requests/sec",
              "refId": "A"
            }
          ],
          "title": "Request Rate",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 10,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "vis": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "never",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "s"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          },
          "id": 4,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "expr": "histogram_quantile(0.95, rate(nginx_http_request_duration_seconds_bucket{service=\"gait-detection-service\"}[5m]))",
              "interval": "",
              "legendFormat": "95th percentile",
              "refId": "A"
            },
            {
              "expr": "histogram_quantile(0.50, rate(nginx_http_request_duration_seconds_bucket{service=\"gait-detection-service\"}[5m]))",
              "interval": "",
              "legendFormat": "50th percentile",
              "refId": "B"
            }
          ],
          "title": "Response Time",
          "type": "timeseries"
        }
      ],
      "refresh": "5s",
      "schemaVersion": 30,
      "style": "dark",
      "tags": ["gait-detection"],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Gait Detection Dashboard",
      "uid": "gait-detection-dashboard",
      "version": 1
    }